import React, { useState } from 'react';
import {
  FileText,
  Download,
  Calendar,
  Filter,
  FileSpreadsheet,
  FileCheck,
  Plus,
  Search,
  ChevronDown,
  Eye,
  Sparkles,
  Share2,
  Clock,
  ShieldCheck,
  CheckCircle2,
  AlertTriangle,
  RefreshCw,
  X,
  Building2,
  Layers,
  ArrowUpRight,
  TrendingUp,
  Mail,
  Printer,
  SlidersHorizontal,
  FileCode,
  Check
} from 'lucide-react';

export interface ReportItem {
  id: string;
  title: string;
  category: 'Executive Audits' | 'Loss Prevention' | 'Staffing & POS' | 'Spatial & Dwell';
  date: string;
  store: string;
  format: 'PDF Audit' | 'CSV Data' | 'XLSX Matrix' | 'AI Summary';
  size: string;
  status: 'Ready' | 'Generating' | 'Scheduled';
  complianceScore: number;
  summary: string;
  keyInsights: string[];
}

export const ReportsView: React.FC = () => {
  const [activeCategory, setActiveCategory] = useState<string>('All Reports');
  const [selectedStore, setSelectedStore] = useState<string>('All Locations');
  const [selectedFormat, setSelectedFormat] = useState<string>('All Formats');
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [selectedReport, setSelectedReport] = useState<ReportItem | null>(null);
  const [isGenerateModalOpen, setIsGenerateModalOpen] = useState<boolean>(false);
  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const [generationStep, setGenerationStep] = useState<string>('');

  // Form state for generating custom report
  const [newReportTitle, setNewReportTitle] = useState<string>('Q4 Retail AI Operational & Loss Prevention Audit');
  const [newReportCategory, setNewReportCategory] = useState<ReportItem['category']>('Executive Audits');
  const [newReportStore, setNewReportStore] = useState<string>('Manhattan Flagship');
  const [newReportFormat, setNewReportFormat] = useState<ReportItem['format']>('PDF Audit');

  const [reportsList, setReportsList] = useState<ReportItem[]>([
    {
      id: 'rep-101',
      title: 'Q3 Executive AI Retail Operational & Loss Audit',
      category: 'Executive Audits',
      date: 'Oct 24, 2026',
      store: 'Manhattan Flagship',
      format: 'PDF Audit',
      size: '4.2 MB',
      status: 'Ready',
      complianceScore: 98.4,
      summary: 'Comprehensive Q3 computer vision analysis across all 12 store locations. Highlights footfall conversion rate of 34.2%, checkout queue friction reductions, and zero critical loss events in high-value zones.',
      keyInsights: [
        'Overall footfall increased by +12.4% year-over-year in Manhattan Flagship.',
        'Checkout queue dwell time decreased by 1m 45s following recommended POS staffing shifts.',
        'AI anomaly detection flagged 3 unauthorized loading dock entries with 100% security dispatch resolution.'
      ]
    },
    {
      id: 'rep-102',
      title: 'Weekly Dwell Friction & Queue Bottleneck Analysis',
      category: 'Staffing & POS',
      date: 'Oct 20, 2026',
      store: 'Brooklyn Heights',
      format: 'CSV Data',
      size: '1.8 MB',
      status: 'Ready',
      complianceScore: 96.1,
      summary: 'Granular 7-day queue telemetry logs from 42 camera feeds targeting POS stations and customer service desks. Identifies peak bottleneck hours between 12:00 PM and 4:00 PM.',
      keyInsights: [
        'POS Station #3 experienced peak wait times exceeding 6 minutes on Saturday afternoon.',
        'Recommended auto-alert trigger at 4+ queue count reduced average customer wait times by 22%.',
        'Customer satisfaction score correlated +18% with reduced queue length.'
      ]
    },
    {
      id: 'rep-103',
      title: 'Regional Footfall & Conversion Telemetry Log',
      category: 'Spatial & Dwell',
      date: 'Oct 15, 2026',
      store: 'All Locations',
      format: 'PDF Audit',
      size: '8.4 MB',
      status: 'Ready',
      complianceScore: 99.2,
      summary: 'Regional spatial density analysis capturing customer navigation heatmaps, aisle engagement rates, and end-cap dwell metrics across Northeast retail centers.',
      keyInsights: [
        'Men Apparel section on Floor 1 saw the highest average dwell time (9m 45s).',
        'Electronics Aisle 3 achieved a 42.1% dwell-to-purchase conversion rate.',
        'Rear aisle footfall increased 15% following promotional end-cap repositioning.'
      ]
    },
    {
      id: 'rep-104',
      title: 'Staff Allocation & POS Efficiency Matrix',
      category: 'Staffing & POS',
      date: 'Oct 08, 2026',
      store: 'Queens Center',
      format: 'XLSX Matrix',
      size: '2.1 MB',
      status: 'Ready',
      complianceScore: 97.8,
      summary: 'Predictive staffing recommendations generated by Gemini AI model based on historical footfall heatmaps and real-time checkout telemetry.',
      keyInsights: [
        'Shifting 2 sales associates to checkout duty between 14:00-16:00 eliminates 85% of queue spillover.',
        'Labor efficiency index improved by +14.2% across Queens location.',
        'Overtime hours reduced by 11.5 hours per week per store.'
      ]
    },
    {
      id: 'rep-105',
      title: 'Loss Prevention & High-Value Zone Telemetry Audit',
      category: 'Loss Prevention',
      date: 'Oct 01, 2026',
      store: 'Manhattan Flagship',
      format: 'PDF Audit',
      size: '5.6 MB',
      status: 'Ready',
      complianceScore: 99.8,
      summary: 'Security & Shrinkage audit monitoring restricted zones, loading docks, and luxury item displays. Integrates camera event logs with staff badge verification.',
      keyInsights: [
        'Zero shrink incidents reported in high-value jewelry display zone.',
        'Restricted door access audit logged 100% authorized personnel entries.',
        'Nighttime perimeter motion detection precision achieved 99.9% true-positive accuracy.'
      ]
    },
    {
      id: 'rep-106',
      title: 'Customer Dwell & Heatmap Traffic Synthesis',
      category: 'Spatial & Dwell',
      date: 'Sep 24, 2026',
      store: 'Brooklyn Heights',
      format: 'AI Summary',
      size: '1.2 MB',
      status: 'Ready',
      complianceScore: 95.5,
      summary: 'AI-synthesized executive brief detailing visual dwell patterns, cold-zone customer drop-offs, and store design optimization suggestions.',
      keyInsights: [
        'Central atrium display attracted 68% of all store footfall.',
        'Cold zone identified in West Wing corner; lighting adjustment recommended.',
        'Cross-merchandising opportunity detected between footwear and accessories.'
      ]
    }
  ]);

  const categories = [
    'All Reports',
    'Executive Audits',
    'Loss Prevention',
    'Staffing & POS',
    'Spatial & Dwell'
  ];

  const filteredReports = reportsList.filter((report) => {
    if (activeCategory !== 'All Reports' && report.category !== activeCategory) return false;
    if (selectedStore !== 'All Locations' && report.store !== selectedStore && report.store !== 'All Locations') return false;
    if (selectedFormat !== 'All Formats' && report.format !== selectedFormat) return false;
    if (searchQuery && !report.title.toLowerCase().includes(searchQuery.toLowerCase()) && !report.summary.toLowerCase().includes(searchQuery.toLowerCase())) {
      return false;
    }
    return true;
  });

  const handleGenerateReport = () => {
    setIsGenerating(true);
    setGenerationStep('Connecting to AI Vision Cluster...');

    setTimeout(() => {
      setGenerationStep('Ingesting camera telemetry & dwell logs...');
    }, 800);

    setTimeout(() => {
      setGenerationStep('Synthesizing executive insights with Gemini...');
    }, 1600);

    setTimeout(() => {
      setGenerationStep('Formatting enterprise PDF & security audit...');
    }, 2400);

    setTimeout(() => {
      const createdReport: ReportItem = {
        id: `rep-${Date.now().toString().slice(-3)}`,
        title: newReportTitle,
        category: newReportCategory,
        date: 'Today, Just Now',
        store: newReportStore,
        format: newReportFormat,
        size: '3.6 MB',
        status: 'Ready',
        complianceScore: 99.5,
        summary: `Freshly compiled computer vision intelligence audit for ${newReportStore}. Ingested live camera telemetry, footfall metrics, and automated AI spatial analysis.`,
        keyInsights: [
          `Footfall conversion benchmarked at optimal baseline for ${newReportStore}.`,
          'Queue wait duration maintained below target 3-minute threshold.',
          'AI edge cameras operating at 100% operational efficiency.'
        ]
      };

      setReportsList([createdReport, ...reportsList]);
      setIsGenerating(false);
      setIsGenerateModalOpen(false);
      setSelectedReport(createdReport);
    }, 3200);
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-300">
      {/* HEADER & ACTION BAR */}
      <section className="flex flex-col md:flex-row md:items-end justify-between gap-6">
        <div>
          <h1 className="text-2xl md:text-3xl font-extrabold text-[#191c1e] tracking-tight">
            Intelligence & Audit Reports
          </h1>
          <p className="text-xs md:text-sm text-[#6B7280] font-medium mt-1 max-w-2xl">
            Automated computer vision audit logs, revenue loss prevention, spatial density telemetry, and staffing optimization reports.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-3 shrink-0">
          <button
            onClick={() => setIsGenerateModalOpen(true)}
            className="flex items-center gap-2 px-4 py-2.5 bg-[#28268d] hover:bg-[#4040a5] text-white rounded-xl text-xs font-bold transition-all shadow-md active:scale-95 cursor-pointer"
          >
            <Sparkles className="w-4 h-4 text-[#F59E0B]" />
            Generate Instant AI Report
          </button>
        </div>
      </section>

      {/* METRICS & OVERVIEW CARDS */}
      <section className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        <div className="bg-white p-5 rounded-2xl border border-[#E5E7EB] shadow-xs hover:shadow-md transition-shadow">
          <div className="flex items-center justify-between mb-3">
            <span className="text-xs font-bold text-[#6B7280]">Total Documents</span>
            <div className="p-2 bg-[#d9dff5] text-[#28268d] rounded-xl">
              <FileText className="w-4 h-4" />
            </div>
          </div>
          <div className="text-2xl font-extrabold text-[#191c1e]">142 Reports</div>
          <p className="text-[11px] text-[#6B7280] font-medium mt-1">12 created this week</p>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-[#E5E7EB] shadow-xs hover:shadow-md transition-shadow">
          <div className="flex items-center justify-between mb-3">
            <span className="text-xs font-bold text-[#6B7280]">Scheduled Audits</span>
            <div className="p-2 bg-[#16A34A]/10 text-[#16A34A] rounded-xl">
              <Clock className="w-4 h-4" />
            </div>
          </div>
          <div className="text-2xl font-extrabold text-[#191c1e]">12 Active Crons</div>
          <p className="text-[11px] text-[#16A34A] font-bold mt-1">Next run: Mon 06:00 AM</p>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-[#E5E7EB] shadow-xs hover:shadow-md transition-shadow">
          <div className="flex items-center justify-between mb-3">
            <span className="text-xs font-bold text-[#6B7280]">AI Insights Logged</span>
            <div className="p-2 bg-[#F59E0B]/10 text-[#F59E0B] rounded-xl">
              <Sparkles className="w-4 h-4" />
            </div>
          </div>
          <div className="text-2xl font-extrabold text-[#191c1e]">1,480 Data Points</div>
          <p className="text-[11px] text-[#6B7280] font-medium mt-1">Synthesized by Gemini</p>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-[#E5E7EB] shadow-xs hover:shadow-md transition-shadow">
          <div className="flex items-center justify-between mb-3">
            <span className="text-xs font-bold text-[#6B7280]">Audit Accuracy</span>
            <div className="p-2 bg-[#e1dfff] text-[#28268d] rounded-xl">
              <ShieldCheck className="w-4 h-4" />
            </div>
          </div>
          <div className="text-2xl font-extrabold text-[#28268d]">99.2% Score</div>
          <p className="text-[11px] text-[#16A34A] font-bold mt-1">Passed Enterprise Audit</p>
        </div>
      </section>

      {/* CATEGORY TABS & FILTER BAR */}
      <section className="bg-white rounded-2xl border border-[#E5E7EB] shadow-xs p-4 space-y-4">
        {/* Category Tabs */}
        <div className="flex items-center gap-2 overflow-x-auto pb-1 scrollbar-none border-b border-[#E5E7EB] px-2">
          {categories.map((cat) => (
            <button
              key={cat}
              onClick={() => setActiveCategory(cat)}
              className={`px-4 py-2 rounded-xl text-xs font-bold whitespace-nowrap transition-all cursor-pointer ${
                activeCategory === cat
                  ? 'bg-[#28268d] text-white shadow-xs'
                  : 'text-[#575e70] hover:bg-[#f2f4f6] hover:text-[#191c1e]'
              }`}
            >
              {cat}
            </button>
          ))}
        </div>

        {/* Filter Toolbar Inputs */}
        <div className="flex flex-wrap items-center justify-between gap-3 pt-1">
          <div className="flex flex-wrap items-center gap-3 flex-1 min-w-[280px]">
            {/* Search Input */}
            <div className="relative flex-1 max-w-md">
              <Search className="w-3.5 h-3.5 absolute left-3 top-1/2 -translate-y-1/2 text-[#6B7280]" />
              <input
                type="text"
                placeholder="Search report titles or insights..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full pl-9 pr-3 py-2 bg-[#f7f9fb] border border-[#E5E7EB] rounded-xl text-xs font-semibold text-[#191c1e] focus:outline-none focus:ring-2 focus:ring-[#28268d]"
              />
            </div>

            {/* Store Filter */}
            <div className="relative">
              <select
                value={selectedStore}
                onChange={(e) => setSelectedStore(e.target.value)}
                className="appearance-none bg-[#f7f9fb] border border-[#E5E7EB] rounded-xl px-3 py-2 pr-8 text-xs font-semibold text-[#191c1e] focus:outline-none focus:ring-2 focus:ring-[#28268d] cursor-pointer"
              >
                <option>All Locations</option>
                <option>Manhattan Flagship</option>
                <option>Brooklyn Heights</option>
                <option>Queens Center</option>
              </select>
              <ChevronDown className="w-3.5 h-3.5 absolute right-2.5 top-1/2 -translate-y-1/2 pointer-events-none text-[#6B7280]" />
            </div>

            {/* Format Filter */}
            <div className="relative">
              <select
                value={selectedFormat}
                onChange={(e) => setSelectedFormat(e.target.value)}
                className="appearance-none bg-[#f7f9fb] border border-[#E5E7EB] rounded-xl px-3 py-2 pr-8 text-xs font-semibold text-[#191c1e] focus:outline-none focus:ring-2 focus:ring-[#28268d] cursor-pointer"
              >
                <option>All Formats</option>
                <option>PDF Audit</option>
                <option>CSV Data</option>
                <option>XLSX Matrix</option>
                <option>AI Summary</option>
              </select>
              <ChevronDown className="w-3.5 h-3.5 absolute right-2.5 top-1/2 -translate-y-1/2 pointer-events-none text-[#6B7280]" />
            </div>
          </div>

          <div className="text-xs text-[#6B7280] font-semibold">
            Showing <span className="text-[#28268d] font-bold">{filteredReports.length}</span> documents
          </div>
        </div>
      </section>

      {/* REPORTS LIST CONTAINER */}
      <section className="bg-white rounded-2xl border border-[#E5E7EB] shadow-xs overflow-hidden">
        <div className="p-4 border-b border-[#E5E7EB] bg-[#f7f9fb] flex items-center justify-between text-xs font-bold text-[#6B7280] uppercase tracking-wider">
          <span>Report Title & Metadata</span>
          <span className="hidden sm:inline">Compliance & Actions</span>
        </div>

        <div className="divide-y divide-[#E5E7EB]">
          {filteredReports.length === 0 ? (
            <div className="p-12 text-center text-[#6B7280] space-y-3">
              <FileText className="w-10 h-10 mx-auto text-[#6B7280]/40" />
              <p className="text-xs font-bold">No reports found matching your selected filters.</p>
              <button
                onClick={() => {
                  setActiveCategory('All Reports');
                  setSelectedStore('All Locations');
                  setSelectedFormat('All Formats');
                  setSearchQuery('');
                }}
                className="px-3.5 py-1.5 bg-[#f2f4f6] text-[#28268d] text-xs font-bold rounded-xl hover:bg-[#d9dff5] transition-colors"
              >
                Reset All Filters
              </button>
            </div>
          ) : (
            filteredReports.map((report) => (
              <div
                key={report.id}
                onClick={() => setSelectedReport(report)}
                className={`p-4 md:p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4 transition-colors cursor-pointer ${
                  selectedReport?.id === report.id
                    ? 'bg-[#d9dff5]/30 border-l-4 border-[#28268d]'
                    : 'hover:bg-[#f7f9fb]'
                }`}
              >
                <div className="flex items-start gap-4 flex-1 min-w-0">
                  <div className="w-10 h-10 rounded-xl bg-[#28268d]/10 text-[#28268d] flex items-center justify-center shrink-0 mt-0.5">
                    {report.format === 'PDF Audit' && <FileText className="w-5 h-5" />}
                    {report.format === 'CSV Data' && <FileSpreadsheet className="w-5 h-5 text-[#16A34A]" />}
                    {report.format === 'XLSX Matrix' && <FileSpreadsheet className="w-5 h-5 text-[#F59E0B]" />}
                    {report.format === 'AI Summary' && <Sparkles className="w-5 h-5 text-[#28268d]" />}
                  </div>

                  <div className="min-w-0 flex-1">
                    <div className="flex flex-wrap items-center gap-2 mb-1">
                      <h4 className="text-xs md:text-sm font-bold text-[#191c1e] hover:text-[#28268d] transition-colors truncate">
                        {report.title}
                      </h4>
                      <span className="px-2 py-0.5 bg-[#f2f4f6] text-[#575e70] rounded-md text-[10px] font-bold">
                        {report.category}
                      </span>
                    </div>

                    <p className="text-xs text-[#575e70] font-medium line-clamp-1 mb-2">
                      {report.summary}
                    </p>

                    <div className="flex flex-wrap items-center gap-3 text-[11px] text-[#6B7280] font-semibold">
                      <span className="flex items-center gap-1">
                        <Calendar className="w-3 h-3 text-[#6B7280]" />
                        {report.date}
                      </span>
                      <span>•</span>
                      <span className="flex items-center gap-1">
                        <Building2 className="w-3 h-3 text-[#6B7280]" />
                        {report.store}
                      </span>
                      <span>•</span>
                      <span className="font-mono text-[#191c1e]">{report.format} ({report.size})</span>
                    </div>
                  </div>
                </div>

                <div className="flex items-center justify-between sm:justify-end gap-4 shrink-0 border-t sm:border-t-0 pt-3 sm:pt-0 border-[#E5E7EB]">
                  <div className="flex items-center gap-2">
                    <span className="text-[11px] font-bold text-[#6B7280]">AI Audit:</span>
                    <span className="px-2.5 py-1 bg-[#16A34A]/10 text-[#16A34A] rounded-lg text-[11px] font-extrabold flex items-center gap-1">
                      <ShieldCheck className="w-3.5 h-3.5" />
                      {report.complianceScore}%
                    </span>
                  </div>

                  <div className="flex items-center gap-2">
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        setSelectedReport(report);
                      }}
                      className="p-2 text-[#28268d] hover:bg-[#28268d]/10 rounded-xl transition-colors cursor-pointer"
                      title="Inspect Report Details"
                    >
                      <Eye className="w-4 h-4" />
                    </button>
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        alert(`Downloading ${report.title} (${report.format})...`);
                      }}
                      className="p-2 text-[#28268d] hover:bg-[#28268d]/10 rounded-xl transition-colors cursor-pointer"
                      title="Download File"
                    >
                      <Download className="w-4 h-4" />
                    </button>
                  </div>
                </div>
              </div>
            ))
          )}
        </div>
      </section>

      {/* SCHEDULED AUTOMATED REPORTS SECTION */}
      <section className="bg-white rounded-2xl border border-[#E5E7EB] shadow-xs p-6 space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="text-base font-extrabold text-[#191c1e]">Automated Report Schedules (Cron)</h3>
            <p className="text-xs text-[#6B7280] font-medium mt-0.5">Recurring computer vision audits sent to executive stakeholders.</p>
          </div>
          <button className="px-3.5 py-1.5 border border-[#E5E7EB] hover:bg-[#f2f4f6] text-[#191c1e] text-xs font-bold rounded-xl transition-colors cursor-pointer flex items-center gap-1.5">
            <Plus className="w-3.5 h-3.5 text-[#28268d]" /> New Schedule
          </button>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="p-4 bg-[#f7f9fb] rounded-xl border border-[#E5E7EB] flex items-center justify-between">
            <div className="space-y-1">
              <div className="flex items-center gap-2">
                <span className="text-xs font-bold text-[#191c1e]">Weekly Executive Operational Brief</span>
                <span className="px-2 py-0.5 bg-[#16A34A]/10 text-[#16A34A] text-[10px] font-bold rounded">ACTIVE</span>
              </div>
              <p className="text-[11px] text-[#6B7280] font-medium">Recipients: executive-board@retailcount.ai • Every Monday @ 06:00 AM</p>
            </div>
            <button className="p-2 text-[#575e70] hover:text-[#28268d] hover:bg-[#E5E7EB] rounded-lg transition-colors cursor-pointer">
              <SlidersHorizontal className="w-4 h-4" />
            </button>
          </div>

          <div className="p-4 bg-[#f7f9fb] rounded-xl border border-[#E5E7EB] flex items-center justify-between">
            <div className="space-y-1">
              <div className="flex items-center gap-2">
                <span className="text-xs font-bold text-[#191c1e]">Daily POS Queue & Dwell Telemetry Audit</span>
                <span className="px-2 py-0.5 bg-[#16A34A]/10 text-[#16A34A] text-[10px] font-bold rounded">ACTIVE</span>
              </div>
              <p className="text-[11px] text-[#6B7280] font-medium">Recipients: store-managers@retailcount.ai • Daily @ 22:00 PM</p>
            </div>
            <button className="p-2 text-[#575e70] hover:text-[#28268d] hover:bg-[#E5E7EB] rounded-lg transition-colors cursor-pointer">
              <SlidersHorizontal className="w-4 h-4" />
            </button>
          </div>
        </div>
      </section>

      {/* REPORT INSPECTOR SIDE DRAWER */}
      {selectedReport && (
        <aside className="fixed top-0 right-0 h-screen w-full sm:w-[480px] bg-white shadow-2xl z-50 border-l border-[#E5E7EB] flex flex-col justify-between overflow-y-auto animate-in slide-in-from-right duration-300">
          <div>
            {/* Drawer Header */}
            <div className="p-6 border-b border-[#E5E7EB] flex items-center justify-between sticky top-0 bg-white/95 backdrop-blur-md z-10">
              <div className="flex items-center gap-2.5">
                <div className="p-2 bg-[#28268d]/10 text-[#28268d] rounded-xl">
                  <FileText className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="text-sm font-extrabold text-[#191c1e]">Report Inspector</h3>
                  <span className="text-[10px] font-bold text-[#6B7280] uppercase tracking-wider">
                    ID: {selectedReport.id}
                  </span>
                </div>
              </div>
              <button
                onClick={() => setSelectedReport(null)}
                className="p-1.5 hover:bg-[#f2f4f6] text-[#6B7280] rounded-lg transition-colors cursor-pointer"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Main Drawer Body */}
            <div className="p-6 space-y-6">
              {/* Title & Badge */}
              <div>
                <span className="px-2.5 py-1 bg-[#28268d]/10 text-[#28268d] text-[10px] font-extrabold rounded-md uppercase tracking-wider">
                  {selectedReport.category}
                </span>
                <h2 className="text-base font-extrabold text-[#191c1e] mt-2 leading-snug">
                  {selectedReport.title}
                </h2>
              </div>

              {/* Metadata Box */}
              <div className="p-4 bg-[#f7f9fb] rounded-2xl border border-[#E5E7EB] space-y-3 text-xs font-medium">
                <div className="flex justify-between items-center">
                  <span className="text-[#6B7280]">Target Store:</span>
                  <span className="font-bold text-[#191c1e]">{selectedReport.store}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-[#6B7280]">Date Generated:</span>
                  <span className="font-bold text-[#191c1e]">{selectedReport.date}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-[#6B7280]">Export Format & Size:</span>
                  <span className="font-mono text-[#28268d] font-bold">{selectedReport.format} ({selectedReport.size})</span>
                </div>
                <div className="flex justify-between items-center pt-2 border-t border-[#E5E7EB]">
                  <span className="text-[#6B7280]">AI Vision Compliance:</span>
                  <span className="text-[#16A34A] font-extrabold flex items-center gap-1">
                    <ShieldCheck className="w-4 h-4" />
                    {selectedReport.complianceScore}% Certified
                  </span>
                </div>
              </div>

              {/* Executive Summary */}
              <div className="space-y-2">
                <h4 className="text-xs font-extrabold text-[#191c1e] uppercase tracking-wider flex items-center gap-1.5">
                  <Sparkles className="w-4 h-4 text-[#28268d]" /> Executive AI Summary
                </h4>
                <p className="text-xs text-[#575e70] leading-relaxed font-medium bg-[#f7f9fb] p-4 rounded-xl border border-[#E5E7EB]">
                  {selectedReport.summary}
                </p>
              </div>

              {/* Key Insights List */}
              <div className="space-y-3">
                <h4 className="text-xs font-extrabold text-[#191c1e] uppercase tracking-wider">
                  Key Findings & Telemetry Highlights
                </h4>
                <div className="space-y-2.5">
                  {selectedReport.keyInsights.map((insight, idx) => (
                    <div key={idx} className="flex items-start gap-3 text-xs text-[#191c1e] font-medium p-3 bg-white border border-[#E5E7EB] rounded-xl shadow-2xs">
                      <CheckCircle2 className="w-4 h-4 text-[#16A34A] shrink-0 mt-0.5" />
                      <span>{insight}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>

          {/* Drawer Footer Actions */}
          <div className="p-6 border-t border-[#E5E7EB] bg-white sticky bottom-0 flex gap-3">
            <button
              onClick={() => alert(`Downloading ${selectedReport.title}...`)}
              className="flex-1 py-3 bg-[#28268d] hover:bg-[#4040a5] text-white rounded-xl text-xs font-bold transition-all shadow-md flex items-center justify-center gap-2 cursor-pointer"
            >
              <Download className="w-4 h-4" /> Download Report
            </button>
            <button
              onClick={() => alert(`Emailing report to account owner...`)}
              className="p-3 border border-[#E5E7EB] hover:bg-[#f2f4f6] text-[#575e70] rounded-xl transition-colors cursor-pointer"
              title="Share / Email"
            >
              <Mail className="w-4 h-4" />
            </button>
            <button
              onClick={() => window.print()}
              className="p-3 border border-[#E5E7EB] hover:bg-[#f2f4f6] text-[#575e70] rounded-xl transition-colors cursor-pointer"
              title="Print Audit"
            >
              <Printer className="w-4 h-4" />
            </button>
          </div>
        </aside>
      )}

      {/* GENERATE CUSTOM AI REPORT MODAL */}
      {isGenerateModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-xs animate-in fade-in duration-200">
          <div className="bg-white w-full max-w-xl rounded-2xl shadow-2xl overflow-hidden border border-[#E5E7EB] space-y-0">
            {/* Modal Header */}
            <div className="p-6 border-b border-[#E5E7EB] flex items-center justify-between bg-[#f7f9fb]">
              <div className="flex items-center gap-2.5">
                <div className="p-2 bg-[#28268d] text-white rounded-xl">
                  <Sparkles className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="text-base font-extrabold text-[#191c1e]">Generate Instant AI Vision Report</h3>
                  <p className="text-xs text-[#6B7280] font-medium">Synthesize computer vision telemetry into executive PDF/CSV audits.</p>
                </div>
              </div>
              {!isGenerating && (
                <button
                  onClick={() => setIsGenerateModalOpen(false)}
                  className="p-1.5 hover:bg-[#e0e3e5] text-[#6B7280] rounded-lg transition-colors cursor-pointer"
                >
                  <X className="w-5 h-5" />
                </button>
              )}
            </div>

            {/* Modal Content */}
            <div className="p-6 space-y-5">
              {isGenerating ? (
                /* Generating Loading State */
                <div className="py-12 flex flex-col items-center justify-center text-center space-y-4">
                  <div className="relative">
                    <div className="w-16 h-16 border-4 border-[#d9dff5] border-t-[#28268d] rounded-full animate-spin" />
                    <Sparkles className="w-6 h-6 text-[#28268d] absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 animate-pulse" />
                  </div>
                  <div>
                    <h4 className="text-sm font-extrabold text-[#191c1e]">Synthesizing AI Audit...</h4>
                    <p className="text-xs font-semibold text-[#28268d] mt-1 font-mono">{generationStep}</p>
                  </div>
                </div>
              ) : (
                /* Form Inputs */
                <>
                  <div className="space-y-1.5">
                    <label className="text-xs font-bold text-[#191c1e]">Report Title</label>
                    <input
                      type="text"
                      value={newReportTitle}
                      onChange={(e) => setNewReportTitle(e.target.value)}
                      className="w-full px-3.5 py-2.5 bg-[#f7f9fb] border border-[#E5E7EB] rounded-xl text-xs font-semibold text-[#191c1e] focus:outline-none focus:ring-2 focus:ring-[#28268d]"
                    />
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div className="space-y-1.5">
                      <label className="text-xs font-bold text-[#191c1e]">Report Category</label>
                      <select
                        value={newReportCategory}
                        onChange={(e) => setNewReportCategory(e.target.value as ReportItem['category'])}
                        className="w-full px-3.5 py-2.5 bg-[#f7f9fb] border border-[#E5E7EB] rounded-xl text-xs font-semibold text-[#191c1e] focus:outline-none focus:ring-2 focus:ring-[#28268d]"
                      >
                        <option>Executive Audits</option>
                        <option>Loss Prevention</option>
                        <option>Staffing & POS</option>
                        <option>Spatial & Dwell</option>
                      </select>
                    </div>

                    <div className="space-y-1.5">
                      <label className="text-xs font-bold text-[#191c1e]">Retail Location</label>
                      <select
                        value={newReportStore}
                        onChange={(e) => setNewReportStore(e.target.value)}
                        className="w-full px-3.5 py-2.5 bg-[#f7f9fb] border border-[#E5E7EB] rounded-xl text-xs font-semibold text-[#191c1e] focus:outline-none focus:ring-2 focus:ring-[#28268d]"
                      >
                        <option>Manhattan Flagship</option>
                        <option>Brooklyn Heights</option>
                        <option>Queens Center</option>
                        <option>All Locations</option>
                      </select>
                    </div>
                  </div>

                  <div className="space-y-1.5">
                    <label className="text-xs font-bold text-[#191c1e]">Export Format</label>
                    <div className="grid grid-cols-4 gap-2">
                      {(['PDF Audit', 'CSV Data', 'XLSX Matrix', 'AI Summary'] as const).map((fmt) => (
                        <button
                          key={fmt}
                          type="button"
                          onClick={() => setNewReportFormat(fmt)}
                          className={`py-2 px-2 rounded-xl text-[11px] font-bold border transition-all cursor-pointer ${
                            newReportFormat === fmt
                              ? 'bg-[#28268d] text-white border-[#28268d]'
                              : 'bg-[#f7f9fb] text-[#575e70] border-[#E5E7EB] hover:bg-[#e0e3e5]'
                          }`}
                        >
                          {fmt}
                        </button>
                      ))}
                    </div>
                  </div>
                </>
              )}
            </div>

            {/* Modal Footer */}
            {!isGenerating && (
              <div className="p-6 border-t border-[#E5E7EB] bg-[#f7f9fb] flex justify-end gap-3">
                <button
                  type="button"
                  onClick={() => setIsGenerateModalOpen(false)}
                  className="px-4 py-2 border border-[#E5E7EB] text-[#575e70] hover:bg-[#e0e3e5] rounded-xl text-xs font-bold transition-colors cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={handleGenerateReport}
                  className="px-5 py-2 bg-[#28268d] hover:bg-[#4040a5] text-white rounded-xl text-xs font-bold transition-all shadow-md cursor-pointer flex items-center gap-2"
                >
                  <Sparkles className="w-4 h-4 text-[#F59E0B]" /> Run Gemini AI Audit
                </button>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};
